[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
bitflags = "1.2.1"
buddy_system_allocator = "0.6"
lock_api = "0.4.6"

[profile.release]
opt-level = "z"
strip = true
lto = true